# Restore escape key
set -s escape-time 5

# Don't repeat inputs without re-leader
set-option -g repeat-time 100

# Enable scrolling using mouse
setw -g mouse on

# Move using hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
