# Enable colored term
set -g default-terminal "tmux-256color"
set-option -sa terminal-features ',xterm-256color:RGB'
set-option -g focus-events on

# Restore escape key
set -s escape-time 5

# Don't repeat inputs without re-leader
set-option -g repeat-time 100

# Enable scrolling using mouse
setw -g mouse on

# Move using hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
